//
// Generated file, do not edit! Created by opp_msgtool 6.0 from mnet/mod/Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Packet;
/**
 * Enum generated from <tt>mnet/mod/Packet.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // Represents a packet in the network.
 * //
 * //packet Packet
 * //{
 * //    int srcAddr \@packetData;
 * //    int destAddr \@packetData;
 * //    int groupAddr \@packetData;
 * //    int aggrCounter \@packetData;
 * //    int aggWin \@packetData; // TODO is here right
 * //    int aggNum \@packetData;
 * //    int hopCount \@packetData;
 * //    unsigned int seq \@packetData;
 * //    unsigned int ackSeq \@packetData;
 * //    bool ECN \@packetData;
 * //}
 * enum PacketType
 * {
 *     ACK = 0;
 *     DATA = 1;
 * }
 * </pre>
 */
enum PacketType {
    ACK = 0,
    DATA = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketType& e) { int n; b->unpack(n); e = static_cast<PacketType>(n); }

/**
 * Class generated from <tt>mnet/mod/Packet.msg:25</tt> by opp_msgtool.
 * <pre>
 * packet Packet
 * {
 *     int64_t connectionId;
 *     int64_t srcAddr;
 *     uint16_t localPort;
 *     int64_t destAddr;
 *     uint16_t destPort;
 *     int64_t seqNumber;
 *     bool ECN;
 *     bool ECE;
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cPacket
{
  protected:
    int64_t connectionId = 0;
    int64_t srcAddr = 0;
    uint16_t localPort = 0;
    int64_t destAddr = 0;
    uint16_t destPort = 0;
    int64_t seqNumber = 0;
    bool ECN = false;
    bool ECE = false;

  private:
    void copy(const Packet& other);

  protected:
    bool operator==(const Packet&) = delete;

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int64_t getConnectionId() const;
    virtual void setConnectionId(int64_t connectionId);

    virtual int64_t getSrcAddr() const;
    virtual void setSrcAddr(int64_t srcAddr);

    virtual uint16_t getLocalPort() const;
    virtual void setLocalPort(uint16_t localPort);

    virtual int64_t getDestAddr() const;
    virtual void setDestAddr(int64_t destAddr);

    virtual uint16_t getDestPort() const;
    virtual void setDestPort(uint16_t destPort);

    virtual int64_t getSeqNumber() const;
    virtual void setSeqNumber(int64_t seqNumber);

    virtual bool getECN() const;
    virtual void setECN(bool ECN);

    virtual bool getECE() const;
    virtual void setECE(bool ECE);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Packet *fromAnyPtr(any_ptr ptr) { return check_and_cast<Packet*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

