//
// Generated file, do not edit! Created by opp_msgtool 6.0 from src/simnet/mod/Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Packet;
/**
 * Enum generated from <tt>src/simnet/mod/Packet.msg:2</tt> by opp_msgtool.
 * <pre>
 * enum PacketType
 * {
 *     ACK = 0;
 *     DATA = 1;
 * } // TODO: I just use pk->getKind() for now, so it's not shown in Packet fields
 * </pre>
 */
enum PacketType {
    ACK = 0,
    DATA = 1
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketType& e) { int n; b->unpack(n); e = static_cast<PacketType>(n); }

/**
 * Class generated from <tt>src/simnet/mod/Packet.msg:8</tt> by opp_msgtool.
 * <pre>
 * packet Packet
 * {
 *     int64_t connectionId;
 *     int64_t srcAddr;
 *     uint16_t localPort;
 *     int64_t destAddr;
 *     uint16_t destPort;
 *     int64_t seqNumber;
 *     int64_t timer;
 *     int32_t aggCounter;
 *     int32_t aggNumber;
 *     double startTime;
 *     double transmitTime;
 *     double queueTime;
 *     bool ECN;
 *     bool ECE;
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cPacket
{
  protected:
    int64_t connectionId = 0;
    int64_t srcAddr = 0;
    uint16_t localPort = 0;
    int64_t destAddr = 0;
    uint16_t destPort = 0;
    int64_t seqNumber = 0;
    int64_t timer = 0;
    int32_t aggCounter = 0;
    int32_t aggNumber = 0;
    double startTime = 0;
    double transmitTime = 0;
    double queueTime = 0;
    bool ECN = false;
    bool ECE = false;

  private:
    void copy(const Packet& other);

  protected:
    bool operator==(const Packet&) = delete;

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int64_t getConnectionId() const;
    virtual void setConnectionId(int64_t connectionId);

    virtual int64_t getSrcAddr() const;
    virtual void setSrcAddr(int64_t srcAddr);

    virtual uint16_t getLocalPort() const;
    virtual void setLocalPort(uint16_t localPort);

    virtual int64_t getDestAddr() const;
    virtual void setDestAddr(int64_t destAddr);

    virtual uint16_t getDestPort() const;
    virtual void setDestPort(uint16_t destPort);

    virtual int64_t getSeqNumber() const;
    virtual void setSeqNumber(int64_t seqNumber);

    virtual int64_t getTimer() const;
    virtual void setTimer(int64_t timer);

    virtual int32_t getAggCounter() const;
    virtual void setAggCounter(int32_t aggCounter);

    virtual int32_t getAggNumber() const;
    virtual void setAggNumber(int32_t aggNumber);

    virtual double getStartTime() const;
    virtual void setStartTime(double startTime);

    virtual double getTransmitTime() const;
    virtual void setTransmitTime(double transmitTime);

    virtual double getQueueTime() const;
    virtual void setQueueTime(double queueTime);

    virtual bool getECN() const;
    virtual void setECN(bool ECN);

    virtual bool getECE() const;
    virtual void setECE(bool ECE);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Packet *fromAnyPtr(any_ptr ptr) { return check_and_cast<Packet*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

